services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge